version: '3.7'
services:
  web:
    build: ./app
    container_name: django-crm-web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7
    container_name: django-crm-db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: django
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    expose:
      - "3307"
    ports:
      - "3307:3306"

